# Generated by Django 5.0.7 on 2024-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marcarConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=255)),
                ('dia', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('plano', models.CharField(max_length=255)),
            ],
        ),
    ]
